name: 'Support requests'

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: ubuntu-20.04
    steps:
      - uses: dessant/support-requests@v3
        with:
          github-token: ${{ github.token }}
          support-label: 'support'
          issue-comment: >
            :wave: @{issue-author}, we use the issue tracker exclusively
            for bug reports and feature requests. However, this issue appears
            to be a support request. Please use our support channels
            to get help with Overseerr.

            - [Discord](https://discord.gg/overseerr)

            - [GitHub Discussions](https://github.com/sct/overseerr/discussions)
          close-issue: true
          lock-issue: true
          issue-lock-reason: 'off-topic'
